Repository SRGSSR/playsrg-apple, pull requests merged in 2023-07, with the labels that each got.

#337 Improve support email body
  Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings
  Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
  Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
  Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings
  Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings
  Application/Sources/Helpers/SupportInformation.swift
Labels: enhancement

#340 Fix quality check with SwiftLint 0.52.4
  Application/Sources/Model/Onboarding.swift
  Application/Sources/Settings/Service.swift
Labels: internal

#341 Rollback Localizable.strings files to UTF-8
  Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings
  Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
  Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
  Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings
  Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings
Labels: internal

#343 Stop player quicker when closing mini player
  Application/Sources/MiniPlayer/PlayMiniPlayerView.m
Labels: minor bug

#346 Add spm-outdated make command to check SPM dependencies
  Makefile
  Scripts/spm-outdated.sh
Labels: internal

#347 CI: update version notification to CI with nighty build number
  fastlane/Fastfile
Labels: internal

#348 Update SwiftUI-Introspect dependency to 0.9.1
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
  Application/Sources/UI/Views/PlayNavigationView.swift
  PlaySRG.xcodeproj/project.pbxproj
  PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: internal

#349 Update CocoaPods to 1.12.1
  Podfile.lock
Labels: internal

#350 Swift conversions
  Application/Sources/Bridges/PlaySRG-ObjectiveC.h
  Application/Sources/Helpers/Categories/NSBundle+PlaySRG.h
  Application/Sources/Helpers/Categories/NSBundle+PlaySRG.m
  Application/Sources/Helpers/Extensions/Bundble+PlaySRG.swift
  Application/Sources/Helpers/Extensions/DateFormatter+playSRG.swift
  Application/Sources/Helpers/Localization.swift
  PlaySRG.xcodeproj/project.pbxproj
  TV Application/Sources/PlaySRG-TV-ObjectiveC.h
Labels: internal

#351 Don't start Firebase if not configured
  Application/Sources/Configuration/PlayFirebaseConfiguration.m
Labels: internal, minor bug

#345 Update image service
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
  Application/Sources/Helpers/Categories/UIImageView+PlaySRG.m
  Application/Sources/Helpers/Extensions.swift
  Application/Sources/Model/Download.m
  Application/Sources/ProgramGuide/ChannelHeaderView.swift
  Application/Sources/ProgramGuide/ProgramViewModel.swift
  Application/Sources/UI/Views/ChannelButton.swift
  Application/Sources/UI/Views/HighlightCell.swift
  Application/Sources/UI/Views/ShowCellViewModel.swift
  Extensions/NotificationService/Sources/NotificationService.m
  PlaySRG.xcodeproj/project.pbxproj
  PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement
