Repository SRGSSR/playsrg-apple, pull requests merged in 2024-04, with the labels that each got.

#449 Deployment status updated after PR closure
  .github/workflows/pr-closure.yml
  .yamllint.yml
Labels: dev tool

#452 Add Jira environment mapping configuration
  .jira/config.yml
Labels: dev tool, internal

#453 Update yaml lint rules and files
  .github/release.yml
  .github/workflows/pr-closure.yml
  .jira/config.yml
  .rubocop.yml
  .swiftlint.yml
  .yamllint.yml
  Scripts/check-quality.sh
Labels: dev tool, internal

#446 Add audio and subtitle selection to support information (PLAYRTS-5498)
  Application/Sources/Helpers/SupportInformation.swift
Labels: improvement

#457 Github pages preview iteration
  fastlane/Fastfile
  fastlane/gh-pages/deployments/build.html
  fastlane/gh-pages/index.html
  fastlane/gh-pages/preview.png
  fastlane/gh-pages/releases/release_notes-beta.html
  fastlane/gh-pages/releases/release_notes-rsi.html
  fastlane/gh-pages/releases/release_notes-rtr.html
  fastlane/gh-pages/releases/release_notes-rts.html
  fastlane/gh-pages/releases/release_notes-srf.html
  fastlane/gh-pages/releases/release_notes-swi.html
Labels: dev tool, internal

#454 Improve beta Github deployments
  fastlane/Fastfile
Labels: dev tool, internal

#455 Move # section to end of AZ list (PLAYRTS-5499)
  Application/Sources/Helpers/Extensions.swift
Labels: bug

#459 Rename Github deployment task
  fastlane/Fastfile
Labels: dev tool, internal

#460 Privacy info manifest update (PLAYRTS-5489)
  Application/Resources/PrivacyInfo.xcprivacy
  TV Application/Resources/PrivacyInfo.xcprivacy
Labels: maintenance

#461 Fix CI build number notification for nightlies
  fastlane/Fastfile
Labels: dev tool, internal

#463 Prepare Github production deployments
  .jira/config.yml
  fastlane/gh-pages/deployments/build.html
  fastlane/gh-pages/deployments/icon_rsi-ios-none.png
  fastlane/gh-pages/deployments/icon_rsi-tvos-none.png
  fastlane/gh-pages/deployments/icon_rtr-ios-none.png
  fastlane/gh-pages/deployments/icon_rtr-tvos-none.png
  fastlane/gh-pages/deployments/icon_rts-ios-none.png
  fastlane/gh-pages/deployments/icon_rts-tvos-none.png
  fastlane/gh-pages/deployments/icon_srf-ios-none.png
  fastlane/gh-pages/deployments/icon_srf-tvos-none.png
  fastlane/gh-pages/deployments/icon_swi-ios-none.png
  fastlane/gh-pages/deployments/icon_swi-tvos-none.png
Labels: dev tool, internal

#462 Github production deployments
  docs/GITHUB_ENVIRONMENTS_AND_DEPLOYMENTS.md
  docs/RELEASE_CHECKLIST.md
  fastlane/Fastfile
  fastlane/README.md
Labels: dev tool, internal

#464 Feature/ci update
  fastlane/Fastfile
Labels: dev tool, internal

#465 Fix Beta and TestFlight tag Github deployments
  fastlane/Fastfile
Labels: dev tool, internal
