Repository SRGSSR/playsrg-apple, pull requests merged in 2024-05, with the labels that each got.

#466 Update branch beta GitHub environments to inactive state
  .github/workflows/pr-closure.yml
  docs/GITHUB_ENVIRONMENTS_AND_DEPLOYMENTS.md
Labels: dev tool, internal

#467 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dev tool

#469 Update Airship license
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist/ios-library.plist
Labels: maintenance, internal

#470 Add shared issue tracker configuration
  .issuetracker
Labels: dev tool, internal

#468 Update design system (PLAYRTS-5514)
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
  Application/Sources/Browser/WebViewController.m
  Application/Sources/Calendar/CalendarViewController.m
  Application/Sources/Content/SectionShowHeaderView.swift
  Application/Sources/Helpers/UserConsentHelper.swift
  Application/Sources/Player/MediaPlayerViewController+SongPanel.swift
  Application/Sources/Player/MediaPlayerViewController.m
  Application/Sources/Player/RelatedContentView.m
  Application/Sources/Profile/ProfileAccountHeaderView.swift
  Application/Sources/Profile/ProfileCell.swift
  Application/Sources/Profile/ProfileHelp.swift
  Application/Sources/Profile/ProfileSectionHeaderView.swift
  Application/Sources/ProgramGuide/ProgramCell.swift
  Application/Sources/ProgramGuide/ProgramGuideHeaderView.swift
  Application/Sources/ProgramGuide/ProgramPreview.swift
  Application/Sources/ProgramGuide/ProgramView.swift
  Application/Sources/Search/SearchViewController.swift
  Application/Sources/UI/Controllers/NavigationController.m
  Application/Sources/UI/Controllers/TableRequestViewController.m
  Application/Sources/UI/Views/ActivityIndicator.swift
  Application/Sources/UI/Views/ChannelButton.swift
  Application/Sources/UI/Views/DiskInfoFooterView.swift
  Application/Sources/UI/Views/DownloadCell.swift
  Application/Sources/UI/Views/EmptyContentView.swift
  Application/Sources/UI/Views/ExpandingButton.swift
  Application/Sources/UI/Views/FeaturedDescriptionView.swift
  Application/Sources/UI/Views/Handle.swift
  Application/Sources/UI/Views/HeaderView.swift
  Application/Sources/UI/Views/MediaCell.swift
  Application/Sources/UI/Views/MediaMoreButton.swift
  Application/Sources/UI/Views/MoreCell.swift
  Application/Sources/UI/Views/NotificationCell.swift
  Application/Sources/UI/Views/SheetTextView.swift
  Application/Sources/UI/Views/ShowButton.swift
  Application/Sources/UI/Views/ShowCell.swift
  Application/Sources/UI/Views/SimpleButton.swift
  Application/Sources/UI/Views/TableLoadMoreFooterView.swift
  Application/Sources/UI/Views/TitleView.swift
  Application/Sources/UI/Views/TransluscentHeaderView.swift
  PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: improvement

#474 Update LicensePlist version
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
Labels: dev tool, internal

#477 Git hook to append Jira issue key (PLAYRTS-5503)
  docs/CONTRIBUTING.md
  docs/README.md
  hooks/commit-msg
Labels: dev tool, internal

#478 Update Universal Link documentation
  docs/CUSTOM_URLS_AND_UNIVERSAL_LINKS.md
Labels: maintenance, internal

#451 Show header update with topic gradient (PLAYRTS-5405 & PLAYRTS-5478)
  Application/Resources/Apps/Play RSI/ApplicationConfiguration.json
  Application/Resources/Apps/Play RTR/ApplicationConfiguration.json
  Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
  Application/Resources/Apps/Play SRF/ApplicationConfiguration.json
  Application/Sources/Configuration/ApplicationConfiguration.h
  Application/Sources/Configuration/ApplicationConfiguration.m
  Application/Sources/Configuration/ApplicationConfiguration.swift
  Application/Sources/Configuration/PlayFirebaseConfiguration.h
  Application/Sources/Configuration/PlayFirebaseConfiguration.m
  Application/Sources/Content/PageViewController.swift
  Application/Sources/Content/PageViewModel.swift
  Application/Sources/Content/SectionViewController.swift
  Application/Sources/Content/ShowHeaderView.swift
  Application/Sources/UI/Helpers/ColorsSettable.swift
  Application/Sources/UI/Helpers/ContextMenu.swift
  Application/Sources/UI/Views/ExpandingButton.swift
  Application/Sources/UI/Views/FeaturedContentCell.swift
  Application/Sources/UI/Views/FeaturedDescriptionView.swift
  Application/Sources/UI/Views/HeaderView.swift
  Application/Sources/UI/Views/MediaCell.swift
  Application/Sources/UI/Views/PageHeaderView.swift
  Application/Sources/UI/Views/ShowAccessCell.swift
  Application/Sources/UI/Views/ShowCell.swift
  Application/Sources/UI/Views/SimpleButton.swift
  Application/Sources/UI/Views/TitleHeaderView.swift
  Application/Sources/UI/Views/TitleView.swift
  Application/Sources/UI/Views/TopicGradientView.swift
  Application/Sources/UI/Views/TruncatableTextView.swift
  PlaySRG.xcodeproj/project.pbxproj
  Preview Content/Preview Assets.xcassets/Topics/SRGTopic_overflow.dataset/topic-rts.json
  Preview Content/Preview Assets.xcassets/Topics/SRGTopic_standard.dataset/topic-rts.json
  TV Application/Sources/LabeledCardButton.swift
  docs/REMOTE_CONFIGURATION.md
Labels: improvement

#480 Update romansh translation
  Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
  Translations/Accessibility.strings
  Translations/Localizable.strings
Labels: maintenance

#481 Improve error message (PLAYRTS-5527)
  Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings
  Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
  Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
  Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings
  Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings
  Application/Sources/Content/PageViewController.swift
  Translations/Localizable.strings
Labels: improvement, internal

#482 CI: clean untracked files when an error occurred
  fastlane/Fastfile
Labels: CI

#476 Fix cell image background (PLAYRTS-5510)
  Application/Sources/Content/SectionShowHeaderView.swift
  Application/Sources/Content/ShowHeaderView.swift
  Application/Sources/Content/ShowHeaderViewModel.swift
  Application/Sources/Helpers/Colors.swift
  Application/Sources/Helpers/Extensions/UIColor+PlaySRG.swift
  Application/Sources/Model/FeaturedContent.swift
  Application/Sources/Player/MediaPlayerViewController.m
  Application/Sources/Player/ProgramTableViewCell.m
  Application/Sources/ProgramGuide/ProgramView.swift
  Application/Sources/UI/Views/MediaVisualView.swift
  Application/Sources/UI/Views/ShowButton.swift
  Application/Sources/UI/Views/ShowCell.swift
  Application/Sources/UI/Views/ShowCellViewModel.swift
  Application/Sources/UI/Views/ShowVisualView.swift
  PlaySRG.xcodeproj/project.pbxproj
Labels: bug

#484 Fix linter with SwiftLint 0.55.1
  Application/Sources/Content/Content.swift
  Application/Sources/Helpers/UserConsentHelper.swift
Labels: maintenance

#485 PLAYRTS-5529 Update RSI topic gradient colors
  Application/Resources/Apps/Play RSI/ApplicationConfiguration.json
  Application/Resources/Apps/Play RTR/ApplicationConfiguration.json
  Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
  Application/Resources/Apps/Play SRF/ApplicationConfiguration.json
Labels: maintenance

#488 PLAYRTS-5528 Update playback end tolerance
  Application/Resources/Apps/Play RSI/ApplicationConfiguration.json
  Application/Resources/Apps/Play RTR/ApplicationConfiguration.json
  Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
  Application/Resources/Apps/Play SRF/ApplicationConfiguration.json
  Application/Resources/Apps/Play SWI/ApplicationConfiguration.json
  docs/REMOTE_CONFIGURATION.md
Labels: improvement
