Repository SRGSSR/playsrg-apple, pull requests merged in 2025-04, with the labels that each got.

#551 [PLAYNEXT-2561] Update SRF dark app icon
  Application/Resources/Apps/Play SRF/SRFResources.xcassets/AppIcon.appiconset/play-srf-app-icon-ios18-dark.png
Labels: maintenance

#552 PLAYNEXT-1985 News livestreams section
  Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
  Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
Labels: improvement

#548 SMAC-485939 Improve radio/TV program display
  .xcode-version
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
  Application/Sources/Player/MediaPlayerViewController.m
  Application/Sources/Player/ProgramTableViewCell.m
  Application/Sources/UI/Views/LiveMediaCellViewModel.swift
  Gemfile
  Gemfile.lock
  Makefile
  PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Podfile.lock
  fastlane/Fastfile
Labels: bug
