Repository SRGSSR/playsrg-apple, pull requests merged in 2025-05, with the labels that each got.

#557 [PLAYNEXT-3091] Update librairies
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Application/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
  PlaySRG.xcodeproj/project.pbxproj
  PlaySRG.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WhatsNew-iOS-beta.json
  WhatsNew-tvOS-beta.json
Labels: maintenance

#558 PLAYNEXT-3096 Add VPN or Proxy detection settings
  Application/Sources/Application/AppDelegate.m
  Application/Sources/Application/SceneDelegate.m
  Application/Sources/Settings/ApplicationSettings+Common.m
  Application/Sources/Settings/ApplicationSettingsConstants.h
  Application/Sources/Settings/ApplicationSettingsConstants.m
  Application/Sources/Settings/ProxyDetection.swift
  Application/Sources/Settings/SettingsView.swift
  Application/Sources/Settings/UserDefaults+ApplicationSettings.swift
  PlaySRG.xcodeproj/project.pbxproj
  TV Application/Sources/AppDelegate.swift
  TV Application/Sources/SceneDelegate.swift
  Translations/Localizable.strings
Labels: improvement, internal

#559 [PLAYNEXT-3121] Fix Shows section title on Videos tab homepage
  Application/Resources/Apps/Play RSI/it.lproj/Localizable.strings
  Application/Resources/Apps/Play RTR/rm.lproj/Localizable.strings
  Application/Resources/Apps/Play RTS/fr.lproj/Localizable.strings
  Application/Resources/Apps/Play SRF/de.lproj/Localizable.strings
  Application/Resources/Apps/Play SWI/en.lproj/Localizable.strings
  Application/Sources/Content/Content.swift
  Application/Sources/Settings/ProxyDetection.swift
  Translations/Localizable.strings
Labels: bug

#561 Add ESC 2025 channel logo
  Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/esc-2025_32 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/esc-2025_32.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/esc-2025_60.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/esc-2025_22 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/esc-2025_22 2.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/esc-2025_22.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/esc-2025-black_32 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/esc-2025-black_32.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/esc-2025-black_60.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/esc-2025-black_22 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/esc-2025-black_22 2.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/esc-2025-black_22.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/esc-2025-lavender_32 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/esc-2025-lavender_32.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/esc-2025-lavender_60.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/esc-2025-lavender_22 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/esc-2025-lavender_22 2.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/esc-2025-lavender_22.pdf
Labels: maintenance

#560 PLAYNEXT-3123 Release 3.9.3
  WhatsNew-iOS-beta.json
  WhatsNew-tvOS-beta.json
Labels: maintenance

#562 Remove ESC 2025 channel logos
  Application/Resources/Apps/Play RTS/ApplicationConfiguration.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/esc-2025_32 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/esc-2025_32.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025-large.imageset/esc-2025_60.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/esc-2025_22 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/esc-2025_22 2.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025.imageset/esc-2025_22.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/esc-2025-black_32 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/esc-2025-black_32.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black-large.imageset/esc-2025-black_60.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/esc-2025-black_22 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/esc-2025-black_22 2.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_black.imageset/esc-2025-black_22.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/esc-2025-lavender_32 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/esc-2025-lavender_32.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender-large.imageset/esc-2025-lavender_60.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/Contents.json
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/esc-2025-lavender_22 1.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/esc-2025-lavender_22 2.pdf
  Application/Resources/Images/CommonImages.xcassets/ESC-2025/logo_esc_2025_lavender.imageset/esc-2025-lavender_22.pdf
Labels: maintenance, internal
